config/routes.rb
SJMTig::Application.routes.draw do
  resources :offices

  resources :wall_plates

  resources :port_panels

  resources :panels

  resources :panel_models

  resources :panel_brands

  resources :network_racks

  resources :hosts

  resources :vlans

  resources :events

  resources :oid_models

  resources :oids

  resources :port_models

  resources :port_types

  resources :switch_ports

  resources :device_details

  resources :device_models

  resources :network_devices

  resources :room_issues

  resources :issues

  resources :rooms

  resources :locations

end

app/models/device_detail.rb
class DeviceDetail < ActiveRecord::Base
  has_many :switch_ports
  belongs_to :device_model
  validates :macAddress, :ipAddress, :osVersion, :presence => true
  validates :macAddress, :length => { :maximum => 17 }
  validates :ipAddress, :length => { :maximum => 15 }

end

app/models/device_model.rb
class DeviceModel < ActiveRecord::Base
  #has_many :device_details, :foreign_key =>'id', :class_name => 'DeviceDetail'
  has_many :port_models
  has_many :port_types, :through => :port_models
  belongs_to :network_device
  has_many :oids, :through => :oid_models
  validates :model, :numberOfPort, :presence => true
  validates :model, :length => { :maximum => 50 }
  validates :numberOfPort, :only_integer, :length => { :maximum => 2 }
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :oid
  belongs_to :switch_port
  validates :name, :activityDate, :presence => true
  validates :name, :length => { :maximum => 100 }
end

app/models/host.rb
class Host < ActiveRecord::Base
  has_one :wall_plate
  belongs_to :vlan
  belongs_to :switch_port
  validates :name, :macAddress, :ipAddress, :presence => true
  validates :macAddress, :length => { :maximum => 17 }
  validates :ipAddress, :length => { :maximum => 15 }
  validates :name, :length => { :maximum => 30 }
end

app/models/issue.rb
class Issue < ActiveRecord::Base
  has_many :rooms
  has_many :rooms, :through => :room_issues
  validates :name, :severity, :description, :presence => true
  validates :description, :length => {maximum => 500}
  validates :name, :severity, :length => {maximum => 20}
end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :rooms
  validates :name, :presence => true
end

app/models/office.rb
class Office < ActiveRecord::Base
  has_many :wall_plates
  validates :name, :presence => true, :length => {maximum => 30}
end

app/models/oid.rb
class Oid < ActiveRecord::Base
  has_many :oid_models
  has_many :device_models, :through => :oid_models
  has_many :events
  has_many :switch_ports, :through => :events
  validates :name, :message, :priorityLevel, :oid, :presence => true
  validates :name, :length => { :maximum => 15 }
end

app/models/oid_model.rb
class OidModel < ActiveRecord::Base
  belongs_to :oid
  belongs_to :device_model
end

app/models/panel.rb
class Panel < ActiveRecord::Base
  has_many :port_panels
  belongs_to :panel_model
  validates :description, :length => {:maximum => 100}
end

app/models/panel_brand.rb
class PanelBrand < ActiveRecord::Base
  has_many :panel_models
  validates :name, :presence => true, :length => {maximum => 20}
  belongs_to :network_rack
end

app/models/panel_model.rb
class PanelModel < ActiveRecord::Base
  has_many :panels
  belongs_to :panel_brand
  validates :name, :numberOfPort, :category, :presence => true
  validates :numberOfPort, :only_integer, :length => {maximum => 2}
  validates :category, :length => {maximum => 3}
  validates :name, :length => {maximum => 20}
end

app/models/port_model.rb
class PortModel < ActiveRecord::Base
  belongs_to :device_model
  belongs_to :port_type
end

app/models/port_panel.rb
class PortPanel < ActiveRecord::Base
  has_one :switch_port
  belongs_to :panel
  validates :identifier, :only_integer, :presence => true
end

app/models/port_type.rb
class PortType < ActiveRecord::Base
  has_many :device_models, :through => :port_models
  has_many :port_models
  validates :name, :presence => true
  validates :name, :length => { :maximum => 15 }

end

app/models/room.rb
class Room < ActiveRecord::Base
  has_many :network_racks
  has_many :issues
  has_many :issues, :through => :room_issues
  belongs_to :location
  validates :name, :presence => true, :length => { :maximum => 20}
end

app/models/room_issue.rb
class RoomIssue < ActiveRecord::Base
  belongs_to :room
  belongs_to :issue
  validates :activityDate, :presence => true
end

app/models/switch_port.rb
class SwitchPort < ActiveRecord::Base
  has_many :oids
  has_many :oids, :through => :events
  belongs_to :vlan
  has_one :host
  belongs_to :port_panel
  validates :name, :macAddress, :status,:presence => true
  validates :macAddress, :length => { :maximum => 17 }
  validates :name, :status,:length => { :maximum => 20}
end

app/models/vlan.rb
class Vlan < ActiveRecord::Base
  has_many :hosts
  has_many :switch_ports
  validates :name, :gateway, :netMask, :tag, :presence => true
  validates :netMask, :gateway, :length => { :maximum => 15 }
  validates :tag ,:length => { :maximum => 3}
end

app/models/wall_plate.rb
class WallPlate < ActiveRecord::Base
  belongs_to :host
  belongs_to :office
end

app/controllers/device_details_controller.rb
class DeviceDetailsController < ApplicationController
  before_action :set_device_detail, only: [:show, :edit, :update, :destroy]

  # GET /device_details
  # GET /device_details.json
  def index
    @device_details = DeviceDetail.all
  end

  # GET /device_details/1
  # GET /device_details/1.json
  def show
  end

  # GET /device_details/new
  def new
    @device_detail = DeviceDetail.new
  end

  # GET /device_details/1/edit
  def edit
  end

  # POST /device_details
  # POST /device_details.json
  def create
    @device_detail = DeviceDetail.new(device_detail_params)

    respond_to do |format|
      if @device_detail.save
        format.html { redirect_to @device_detail, notice: 'Device detail was successfully created.' }
        format.json { render action: 'show', status: :created, location: @device_detail }
      else
        format.html { render action: 'new' }
        format.json { render json: @device_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /device_details/1
  # PATCH/PUT /device_details/1.json
  def update
    respond_to do |format|
      if @device_detail.update(device_detail_params)
        format.html { redirect_to @device_detail, notice: 'Device detail was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @device_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /device_details/1
  # DELETE /device_details/1.json
  def destroy
    @device_detail.destroy
    respond_to do |format|
      format.html { redirect_to device_details_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_device_detail
      @device_detail = DeviceDetail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def device_detail_params
      params.require(:device_detail).permit(:macAddress, :ipAddress, :osVersion, :function)
    end
end

app/helpers/device_details_helper.rb
module DeviceDetailsHelper
end

app/helpers/oids_helper.rb
module OidsHelper
end

app/views/device_details/_form.html.erb
<%= form_for(@device_detail) do |f| %>
  <% if @device_detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@device_detail.errors.count, "error") %> prohibited this device_detail from being saved:</h2>

      <ul>
      <% @device_detail.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :macAddress %><br>
    <%= f.text_field :macAddress %>
  </div>
  <div class="field">
    <%= f.label :ipAddress %><br>
    <%= f.text_field :ipAddress %>
  </div>
  <div class="field">
    <%= f.label :osVersion %><br>
    <%= f.text_field :osVersion %>
  </div>
  <div class="field">
    <%= f.label :function %><br>
    <%= f.text_area :function %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/device_details/edit.html.erb
<h1>Editing device_detail</h1>

<%= render 'form' %>

<%= link_to 'Show', @device_detail %> |
<%= link_to 'Back', device_details_path %>

app/views/device_details/index.html.erb
<h1>Listing device_details</h1>

<table>
  <thead>
    <tr>
      <th>Macaddress</th>
      <th>Ipaddress</th>
      <th>Osversion</th>
      <th>Function</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @device_details.each do |device_detail| %>
      <tr>
        <td><%= device_detail.macAddress %></td>
        <td><%= device_detail.ipAddress %></td>
        <td><%= device_detail.osVersion %></td>
        <td><%= device_detail.function %></td>
        <td><%= link_to 'Show', device_detail %></td>
        <td><%= link_to 'Edit', edit_device_detail_path(device_detail) %></td>
        <td><%= link_to 'Destroy', device_detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Device detail', new_device_detail_path %>

app/views/device_details/new.html.erb
<h1>New device_detail</h1>

<%= render 'form' %>

<%= link_to 'Back', device_details_path %>

app/views/device_details/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Macaddress:</strong>
  <%= @device_detail.macAddress %>
</p>

<p>
  <strong>Ipaddress:</strong>
  <%= @device_detail.ipAddress %>
</p>

<p>
  <strong>Osversion:</strong>
  <%= @device_detail.osVersion %>
</p>

<p>
  <strong>Function:</strong>
  <%= @device_detail.function %>
</p>

<%= link_to 'Edit', edit_device_detail_path(@device_detail) %> |
<%= link_to 'Back', device_details_path %>