config/routes.rb
SJMTig::Application.routes.draw do
  resources :offices

  resources :wall_plates

  resources :port_panels

  resources :panels

  resources :panel_models

  resources :panel_brands

  resources :network_racks

  resources :hosts

  resources :vlans

  resources :events

  resources :oid_models

  resources :oids

  resources :port_models

  resources :port_types

  resources :switch_ports

  resources :device_details

  resources :device_models

  resources :network_devices

  resources :room_issues

  resources :issues

  resources :rooms

  resources :locations

end

app/models/device_model.rb
class DeviceModel < ActiveRecord::Base
  #has_many :device_details, :foreign_key =>'id', :class_name => 'DeviceDetail'
  has_many :port_models
  has_many :port_types, :through => :port_models
  belongs_to :network_device
  has_many :oids, :through => :oid_models
  validates :model, :numberOfPort, :presence => true
  validates :model, :length => { :maximum => 50 }
  validates :numberOfPort, :only_integer, :length => { :maximum => 2 }
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :oid
  belongs_to :switch_port
  validates :name, :activityDate, :presence => true
  validates :name, :length => { :maximum => 100 }
end

app/models/host.rb
class Host < ActiveRecord::Base
  has_one :wall_plate
  belongs_to :vlan
  belongs_to :switch_port
  validates :name, :macAddress, :ipAddress, :presence => true
  validates :macAddress, :length => { :maximum => 17 }
  validates :ipAddress, :length => { :maximum => 15 }
  validates :name, :length => { :maximum => 30 }
end

app/models/issue.rb
class Issue < ActiveRecord::Base
  has_many :rooms
  has_many :rooms, :through => :room_issues
  validates :name, :severity, :description, :presence => true
  validates :description, :length => {maximum => 500}
  validates :name, :severity, :length => {maximum => 20}
end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :rooms
  validates :name, :presence => true
end

app/models/office.rb
class Office < ActiveRecord::Base
  has_many :wall_plates
  validates :name, :presence => true, :length => {maximum => 30}
end

app/models/oid.rb
class Oid < ActiveRecord::Base
  has_many :oid_models
  has_many :device_models, :through => :oid_models
  has_many :events
  has_many :switch_ports, :through => :events
  validates :name, :message, :priorityLevel, :oid, :presence => true
  validates :name, :length => { :maximum => 15 }
end

app/models/oid_model.rb
class OidModel < ActiveRecord::Base
  belongs_to :oid
  belongs_to :device_model
end

app/models/panel.rb
class Panel < ActiveRecord::Base
  has_many :port_panels
  belongs_to :panel_model
  validates :description, :length => {:maximum => 100}
end

app/models/panel_brand.rb
class PanelBrand < ActiveRecord::Base
  has_many :panel_models
  validates :name, :presence => true, :length => {maximum => 20}
  belongs_to :network_rack
end

app/models/panel_model.rb
class PanelModel < ActiveRecord::Base
  has_many :panels
  belongs_to :panel_brand
  validates :name, :numberOfPort, :category, :presence => true
  validates :numberOfPort, :only_integer, :length => {maximum => 2}
  validates :category, :length => {maximum => 3}
  validates :name, :length => {maximum => 20}
end

app/models/port_model.rb
class PortModel < ActiveRecord::Base
  belongs_to :device_model
  belongs_to :port_type
end

app/models/port_panel.rb
class PortPanel < ActiveRecord::Base
  has_one :switch_port
  belongs_to :panel
  validates :identifier, :only_integer, :presence => true
end

app/models/port_type.rb
class PortType < ActiveRecord::Base
  has_many :device_models, :through => :port_models
  has_many :port_models
  validates :name, :presence => true
  validates :name, :length => { :maximum => 15 }

end

app/models/room.rb
class Room < ActiveRecord::Base
  has_many :network_racks
  has_many :issues
  has_many :issues, :through => :room_issues
  belongs_to :location
  validates :name, :presence => true, :length => { :maximum => 20}
end

app/models/room_issue.rb
class RoomIssue < ActiveRecord::Base
  belongs_to :room
  belongs_to :issue
  validates :activityDate, :presence => true
end

app/models/switch_port.rb
class SwitchPort < ActiveRecord::Base
  has_many :oids
  has_many :oids, :through => :events
  belongs_to :vlan
  has_one :host
  belongs_to :port_panel
  validates :name, :macAddress, :status,:presence => true
  validates :macAddress, :length => { :maximum => 17 }
  validates :name, :status,:length => { :maximum => 20}
end

app/models/vlan.rb
class Vlan < ActiveRecord::Base
  has_many :hosts
  has_many :switch_ports
  validates :name, :gateway, :netMask, :tag, :presence => true
  validates :netMask, :gateway, :length => { :maximum => 15 }
  validates :tag ,:length => { :maximum => 3}
end

app/models/wall_plate.rb
class WallPlate < ActiveRecord::Base
  belongs_to :host
  belongs_to :office
end

app/controllers/port_types_controller.rb
class PortTypesController < ApplicationController
  before_action :set_port_type, only: [:show, :edit, :update, :destroy]

  # GET /port_types
  # GET /port_types.json
  def index
    @port_types = PortType.all
  end

  # GET /port_types/1
  # GET /port_types/1.json
  def show
  end

  # GET /port_types/new
  def new
    @port_type = PortType.new
  end

  # GET /port_types/1/edit
  def edit
  end

  # POST /port_types
  # POST /port_types.json
  def create
    @port_type = PortType.new(port_type_params)

    respond_to do |format|
      if @port_type.save
        format.html { redirect_to @port_type, notice: 'Port type was successfully created.' }
        format.json { render action: 'show', status: :created, location: @port_type }
      else
        format.html { render action: 'new' }
        format.json { render json: @port_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /port_types/1
  # PATCH/PUT /port_types/1.json
  def update
    respond_to do |format|
      if @port_type.update(port_type_params)
        format.html { redirect_to @port_type, notice: 'Port type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @port_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /port_types/1
  # DELETE /port_types/1.json
  def destroy
    @port_type.destroy
    respond_to do |format|
      format.html { redirect_to port_types_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_port_type
      @port_type = PortType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def port_type_params
      params.require(:port_type).permit(:name, :type)
    end
end

app/helpers/oids_helper.rb
module OidsHelper
end

app/helpers/port_types_helper.rb
module PortTypesHelper
end

app/views/port_types/_form.html.erb
<%= form_for(@port_type) do |f| %>
  <% if @port_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@port_type.errors.count, "error") %> prohibited this port_type from being saved:</h2>

      <ul>
      <% @port_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/port_types/edit.html.erb
<h1>Editing port_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @port_type %> |
<%= link_to 'Back', port_types_path %>

app/views/port_types/index.html.erb
<h1>Listing port_types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @port_types.each do |port_type| %>
      <tr>
        <td><%= port_type.name %></td>
        <td><%= port_type.type %></td>
        <td><%= link_to 'Show', port_type %></td>
        <td><%= link_to 'Edit', edit_port_type_path(port_type) %></td>
        <td><%= link_to 'Destroy', port_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Port type', new_port_type_path %>

app/views/port_types/new.html.erb
<h1>New port_type</h1>

<%= render 'form' %>

<%= link_to 'Back', port_types_path %>

app/views/port_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @port_type.name %>
</p>

<p>
  <strong>Type:</strong>
  <%= @port_type.type %>
</p>

<%= link_to 'Edit', edit_port_type_path(@port_type) %> |
<%= link_to 'Back', port_types_path %>