config/routes.rb
SJMTig::Application.routes.draw do
  resources :offices

  resources :wall_plates

  resources :port_panels

  resources :panels

  resources :panel_models

  resources :panel_brands

  resources :network_racks

  resources :hosts

  resources :vlans

  resources :events

  resources :oid_models

  resources :oids

  resources :port_models

  resources :port_types

  resources :switch_ports

  resources :device_details

  resources :device_models

  resources :network_devices

  resources :room_issues

  resources :issues

  resources :rooms

  resources :locations

end

app/models/device_model.rb
class DeviceModel < ActiveRecord::Base
  #has_many :device_details, :foreign_key =>'id', :class_name => 'DeviceDetail'
  has_many :port_models
  has_many :port_types, :through => :port_models
  belongs_to :network_device
  has_many :oids, :through => :oid_models
  validates :model, :numberOfPort, :presence => true
  validates :model, :length => { :maximum => 50 }
  validates :numberOfPort, :only_integer, :length => { :maximum => 2 }
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :oid
  belongs_to :switch_port
  validates :name, :activityDate, :presence => true
  validates :name, :length => { :maximum => 100 }
end

app/models/host.rb
class Host < ActiveRecord::Base
  has_one :wall_plate
  belongs_to :vlan
  belongs_to :switch_port
  validates :name, :macAddress, :ipAddress, :presence => true
  validates :macAddress, :length => { :maximum => 17 }
  validates :ipAddress, :length => { :maximum => 15 }
  validates :name, :length => { :maximum => 30 }
end

app/models/issue.rb
class Issue < ActiveRecord::Base
  has_many :rooms
  has_many :rooms, :through => :room_issues
  validates :name, :severity, :description, :presence => true
  validates :description, :length => {maximum => 500}
  validates :name, :severity, :length => {maximum => 20}
end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :rooms
  validates :name, :presence => true
end

app/models/network_rack.rb
class NetworkRack < ActiveRecord::Base
  has_many :panel_brands
  validates :name, :type, :presence => true, :length => {maximum => 15}
  belongs_to :room
end

app/models/office.rb
class Office < ActiveRecord::Base
  has_many :wall_plates
  validates :name, :presence => true, :length => {maximum => 30}
end

app/models/oid.rb
class Oid < ActiveRecord::Base
  has_many :oid_models
  has_many :device_models, :through => :oid_models
  has_many :events
  has_many :switch_ports, :through => :events
  validates :name, :message, :priorityLevel, :oid, :presence => true
  validates :name, :length => { :maximum => 15 }
end

app/models/oid_model.rb
class OidModel < ActiveRecord::Base
  belongs_to :oid
  belongs_to :device_model
end

app/models/panel.rb
class Panel < ActiveRecord::Base
  has_many :port_panels
  belongs_to :panel_model
  validates :description, :length => {:maximum => 100}
end

app/models/panel_brand.rb
class PanelBrand < ActiveRecord::Base
  has_many :panel_models
  validates :name, :presence => true, :length => {maximum => 20}
  belongs_to :network_rack
end

app/models/panel_model.rb
class PanelModel < ActiveRecord::Base
  has_many :panels
  belongs_to :panel_brand
  validates :name, :numberOfPort, :category, :presence => true
  validates :numberOfPort, :only_integer, :length => {maximum => 2}
  validates :category, :length => {maximum => 3}
  validates :name, :length => {maximum => 20}
end

app/models/port_model.rb
class PortModel < ActiveRecord::Base
  belongs_to :device_model
  belongs_to :port_type
end

app/models/port_panel.rb
class PortPanel < ActiveRecord::Base
  has_one :switch_port
  belongs_to :panel
  validates :identifier, :only_integer, :presence => true
end

app/models/port_type.rb
class PortType < ActiveRecord::Base
  has_many :device_models, :through => :port_models
  has_many :port_models
  validates :name, :presence => true
  validates :name, :length => { :maximum => 15 }

end

app/models/room.rb
class Room < ActiveRecord::Base
  has_many :network_racks
  has_many :issues
  has_many :issues, :through => :room_issues
  belongs_to :location
  validates :name, :presence => true, :length => { :maximum => 20}
end

app/models/room_issue.rb
class RoomIssue < ActiveRecord::Base
  belongs_to :room
  belongs_to :issue
  validates :activityDate, :presence => true
end

app/models/switch_port.rb
class SwitchPort < ActiveRecord::Base
  has_many :oids
  has_many :oids, :through => :events
  belongs_to :vlan
  has_one :host
  belongs_to :port_panel
  validates :name, :macAddress, :status,:presence => true
  validates :macAddress, :length => { :maximum => 17 }
  validates :name, :status,:length => { :maximum => 20}
end

app/models/vlan.rb
class Vlan < ActiveRecord::Base
  has_many :hosts
  has_many :switch_ports
  validates :name, :gateway, :netMask, :tag, :presence => true
  validates :netMask, :gateway, :length => { :maximum => 15 }
  validates :tag ,:length => { :maximum => 3}
end

app/models/wall_plate.rb
class WallPlate < ActiveRecord::Base
  belongs_to :host
  belongs_to :office
end

app/controllers/switch_ports_controller.rb
class SwitchPortsController < ApplicationController
  before_action :set_switch_port, only: [:show, :edit, :update, :destroy]

  # GET /switch_ports
  # GET /switch_ports.json
  def index
    @switch_ports = SwitchPort.all
  end

  # GET /switch_ports/1
  # GET /switch_ports/1.json
  def show
  end

  # GET /switch_ports/new
  def new
    @switch_port = SwitchPort.new
  end

  # GET /switch_ports/1/edit
  def edit
  end

  # POST /switch_ports
  # POST /switch_ports.json
  def create
    @switch_port = SwitchPort.new(switch_port_params)

    respond_to do |format|
      if @switch_port.save
        format.html { redirect_to @switch_port, notice: 'Switch port was successfully created.' }
        format.json { render action: 'show', status: :created, location: @switch_port }
      else
        format.html { render action: 'new' }
        format.json { render json: @switch_port.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /switch_ports/1
  # PATCH/PUT /switch_ports/1.json
  def update
    respond_to do |format|
      if @switch_port.update(switch_port_params)
        format.html { redirect_to @switch_port, notice: 'Switch port was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @switch_port.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /switch_ports/1
  # DELETE /switch_ports/1.json
  def destroy
    @switch_port.destroy
    respond_to do |format|
      format.html { redirect_to switch_ports_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_switch_port
      @switch_port = SwitchPort.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def switch_port_params
      params.require(:switch_port).permit(:name, :macAddress, :status, :description)
    end
end

app/helpers/oids_helper.rb
module OidsHelper
end

app/helpers/switch_ports_helper.rb
module SwitchPortsHelper
end

app/views/switch_ports/_form.html.erb
<%= form_for(@switch_port) do |f| %>
  <% if @switch_port.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@switch_port.errors.count, "error") %> prohibited this switch_port from being saved:</h2>

      <ul>
      <% @switch_port.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :macAddress %><br>
    <%= f.text_field :macAddress %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/switch_ports/edit.html.erb
<h1>Editing switch_port</h1>

<%= render 'form' %>

<%= link_to 'Show', @switch_port %> |
<%= link_to 'Back', switch_ports_path %>

app/views/switch_ports/index.html.erb
<h1>Listing switch_ports</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Macaddress</th>
      <th>Status</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @switch_ports.each do |switch_port| %>
      <tr>
        <td><%= switch_port.name %></td>
        <td><%= switch_port.macAddress %></td>
        <td><%= switch_port.status %></td>
        <td><%= switch_port.description %></td>
        <td><%= link_to 'Show', switch_port %></td>
        <td><%= link_to 'Edit', edit_switch_port_path(switch_port) %></td>
        <td><%= link_to 'Destroy', switch_port, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Switch port', new_switch_port_path %>

app/views/switch_ports/new.html.erb
<h1>New switch_port</h1>

<%= render 'form' %>

<%= link_to 'Back', switch_ports_path %>

app/views/switch_ports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @switch_port.name %>
</p>

<p>
  <strong>Macaddress:</strong>
  <%= @switch_port.macAddress %>
</p>

<p>
  <strong>Status:</strong>
  <%= @switch_port.status %>
</p>

<p>
  <strong>Description:</strong>
  <%= @switch_port.description %>
</p>

<%= link_to 'Edit', edit_switch_port_path(@switch_port) %> |
<%= link_to 'Back', switch_ports_path %>