config/routes.rb
SJMTig::Application.routes.draw do
  resources :offices

  resources :wall_plates

  resources :port_panels

  resources :panels

  resources :panel_models

  resources :panel_brands

  resources :network_racks

  resources :hosts

  resources :vlans

  resources :events

  resources :oid_models

  resources :oids

  resources :port_models

  resources :port_types

  resources :switch_ports

  resources :device_details

  resources :device_models

  resources :network_devices

  resources :room_issues

  resources :issues

  resources :rooms

  resources :locations

end

app/models/device_model.rb
class DeviceModel < ActiveRecord::Base
  #has_many :device_details, :foreign_key =>'id', :class_name => 'DeviceDetail'
  has_many :port_models
  has_many :port_types, :through => :port_models
  belongs_to :network_device
  has_many :oids, :through => :oid_models
  validates :model, :numberOfPort, :presence => true
  validates :model, :length => { :maximum => 50 }
  validates :numberOfPort, :only_integer, :length => { :maximum => 2 }
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :oid
  belongs_to :switch_port
  validates :name, :activityDate, :presence => true
  validates :name, :length => { :maximum => 100 }
end

app/models/host.rb
class Host < ActiveRecord::Base
  has_one :wall_plate
  belongs_to :vlan
  belongs_to :switch_port
  validates :name, :macAddress, :ipAddress, :presence => true
  validates :macAddress, :length => { :maximum => 17 }
  validates :ipAddress, :length => { :maximum => 15 }
  validates :name, :length => { :maximum => 30 }
end

app/models/issue.rb
class Issue < ActiveRecord::Base
  has_many :rooms
  has_many :rooms, :through => :room_issues
  validates :name, :severity, :description, :presence => true
  validates :description, :length => {maximum => 500}
  validates :name, :severity, :length => {maximum => 20}
end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :rooms
  validates :name, :presence => true
end

app/models/network_rack.rb
class NetworkRack < ActiveRecord::Base
  has_many :panel_brands
  validates :name, :type, :presence => true, :length => {maximum => 15}
  belongs_to :room
end

app/models/office.rb
class Office < ActiveRecord::Base
  has_many :wall_plates
  validates :name, :presence => true, :length => {maximum => 30}
end

app/models/oid.rb
class Oid < ActiveRecord::Base
  has_many :oid_models
  has_many :device_models, :through => :oid_models
  has_many :events
  has_many :switch_ports, :through => :events
  validates :name, :message, :priorityLevel, :oid, :presence => true
  validates :name, :length => { :maximum => 15 }
end

app/models/oid_model.rb
class OidModel < ActiveRecord::Base
  belongs_to :oid
  belongs_to :device_model
end

app/models/panel.rb
class Panel < ActiveRecord::Base
  has_many :port_panels
  belongs_to :panel_model
  validates :description, :length => {:maximum => 100}
end

app/models/panel_brand.rb
class PanelBrand < ActiveRecord::Base
  has_many :panel_models
  validates :name, :presence => true, :length => {maximum => 20}
  belongs_to :network_rack
end

app/models/panel_model.rb
class PanelModel < ActiveRecord::Base
  has_many :panels
  belongs_to :panel_brand
  validates :name, :numberOfPort, :category, :presence => true
  validates :numberOfPort, :only_integer, :length => {maximum => 2}
  validates :category, :length => {maximum => 3}
  validates :name, :length => {maximum => 20}
end

app/models/port_model.rb
class PortModel < ActiveRecord::Base
  belongs_to :device_model
  belongs_to :port_type
end

app/models/port_panel.rb
class PortPanel < ActiveRecord::Base
  has_one :switch_port
  belongs_to :panel
  validates :identifier, :only_integer, :presence => true
end

app/models/port_type.rb
class PortType < ActiveRecord::Base
  has_many :device_models, :through => :port_models
  has_many :port_models
  validates :name, :presence => true
  validates :name, :length => { :maximum => 15 }

end

app/models/room.rb
class Room < ActiveRecord::Base
  has_many :network_racks
  has_many :issues
  has_many :issues, :through => :room_issues
  belongs_to :location
  validates :name, :presence => true, :length => { :maximum => 20}
end

app/models/room_issue.rb
class RoomIssue < ActiveRecord::Base
  belongs_to :room
  belongs_to :issue
  validates :activityDate, :presence => true
end

app/models/switch_port.rb
class SwitchPort < ActiveRecord::Base
  has_many :oids
  has_many :oids, :through => :events
  belongs_to :vlan
  has_one :host
  belongs_to :port_panel
  validates :name, :macAddress, :status,:presence => true
  validates :macAddress, :length => { :maximum => 17 }
  validates :name, :status,:length => { :maximum => 20}
end

app/models/vlan.rb
class Vlan < ActiveRecord::Base
  has_many :hosts
  has_many :switch_ports
  validates :name, :gateway, :netMask, :tag, :presence => true
  validates :netMask, :gateway, :length => { :maximum => 15 }
  validates :tag ,:length => { :maximum => 3}
end

app/models/wall_plate.rb
class WallPlate < ActiveRecord::Base
  belongs_to :host
  belongs_to :office
end

app/controllers/panel_models_controller.rb
class PanelModelsController < ApplicationController
  before_action :set_panel_model, only: [:show, :edit, :update, :destroy]

  # GET /panel_models
  # GET /panel_models.json
  def index
    @panel_models = PanelModel.all
  end

  # GET /panel_models/1
  # GET /panel_models/1.json
  def show
  end

  # GET /panel_models/new
  def new
    @panel_model = PanelModel.new
  end

  # GET /panel_models/1/edit
  def edit
  end

  # POST /panel_models
  # POST /panel_models.json
  def create
    @panel_model = PanelModel.new(panel_model_params)

    respond_to do |format|
      if @panel_model.save
        format.html { redirect_to @panel_model, notice: 'Panel model was successfully created.' }
        format.json { render action: 'show', status: :created, location: @panel_model }
      else
        format.html { render action: 'new' }
        format.json { render json: @panel_model.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /panel_models/1
  # PATCH/PUT /panel_models/1.json
  def update
    respond_to do |format|
      if @panel_model.update(panel_model_params)
        format.html { redirect_to @panel_model, notice: 'Panel model was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @panel_model.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /panel_models/1
  # DELETE /panel_models/1.json
  def destroy
    @panel_model.destroy
    respond_to do |format|
      format.html { redirect_to panel_models_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_panel_model
      @panel_model = PanelModel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def panel_model_params
      params.require(:panel_model).permit(:name, :numberOfPort, :category)
    end
end

app/helpers/oids_helper.rb
module OidsHelper
end

app/helpers/panel_models_helper.rb
module PanelModelsHelper
end

app/views/panel_models/_form.html.erb
<%= form_for(@panel_model) do |f| %>
  <% if @panel_model.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@panel_model.errors.count, "error") %> prohibited this panel_model from being saved:</h2>

      <ul>
      <% @panel_model.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :numberOfPort %><br>
    <%= f.number_field :numberOfPort %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/panel_models/edit.html.erb
<h1>Editing panel_model</h1>

<%= render 'form' %>

<%= link_to 'Show', @panel_model %> |
<%= link_to 'Back', panel_models_path %>

app/views/panel_models/index.html.erb
<h1>Listing panel_models</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Numberofport</th>
      <th>Category</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @panel_models.each do |panel_model| %>
      <tr>
        <td><%= panel_model.name %></td>
        <td><%= panel_model.numberOfPort %></td>
        <td><%= panel_model.category %></td>
        <td><%= link_to 'Show', panel_model %></td>
        <td><%= link_to 'Edit', edit_panel_model_path(panel_model) %></td>
        <td><%= link_to 'Destroy', panel_model, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Panel model', new_panel_model_path %>

app/views/panel_models/new.html.erb
<h1>New panel_model</h1>

<%= render 'form' %>

<%= link_to 'Back', panel_models_path %>

app/views/panel_models/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @panel_model.name %>
</p>

<p>
  <strong>Numberofport:</strong>
  <%= @panel_model.numberOfPort %>
</p>

<p>
  <strong>Category:</strong>
  <%= @panel_model.category %>
</p>

<%= link_to 'Edit', edit_panel_model_path(@panel_model) %> |
<%= link_to 'Back', panel_models_path %>